services:
  cygor:
    build: .
    container_name: cygor
    command: web start --host 0.0.0.0 --port ${CYGOR_PORT:-8080} --load-dir /app/results
    volumes:
      - ${CYGOR_RESULTS_PATH}:/app/results
    network_mode: "host"
    stdin_open: true
    tty: true
    environment:
      - CYGOR_PORT=${CYGOR_PORT:-8080}
