"""
Cygor Module Schema Definitions
===============================

Pydantic models for validating cygor-result.json output format.
This schema enables self-describing module output that the web UI
can render automatically without per-module templates.

Usage:
    from cygor.modules.schema import CygorResult, ModuleInfo, SchemaDefinition

    # Validate existing JSON
    result = CygorResult.model_validate(json_data)

    # Create programmatically
    result = CygorResult(
        module=ModuleInfo(name="My Module", slug="mymodule"),
        schema=SchemaDefinition(view="table", columns=[...]),
        results=[{"host": "192.168.1.1", "status": "open"}]
    )
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field, field_validator


# ----------------------------------------------------------------------
# Enums
# ----------------------------------------------------------------------
class ViewType(str, Enum):
    """Display modes for module results in the web UI."""
    TABLE = "table"
    GALLERY = "gallery"
    MIXED = "mixed"


class ColumnType(str, Enum):
    """Data types for schema columns, affecting how they render."""
    STRING = "string"      # Plain text
    IP = "ip"              # IP address (linkable to host detail)
    URL = "url"            # Clickable hyperlink
    BADGE = "badge"        # Colored status badge
    CODE = "code"          # Monospace/preformatted text
    SCREENSHOT = "screenshot"  # Thumbnail with lightbox


class ModuleCategory(str, Enum):
    """Categories for grouping modules in the web UI."""
    SCREENSHOTS = "screenshots"
    NETWORK_SHARES = "network-shares"
    ENUMERATION = "enumeration"
    CREDENTIALS = "credentials"
    CUSTOM = "custom"


# ----------------------------------------------------------------------
# Schema Components
# ----------------------------------------------------------------------
class ColumnDefinition(BaseModel):
    """Defines a single column in the results schema."""
    key: str = Field(..., description="JSON key in result objects")
    label: str = Field(..., description="Human-readable column header")
    type: ColumnType = Field(default=ColumnType.STRING, description="Data type for rendering")
    sortable: bool = Field(default=True, description="Whether column is sortable")
    filterable: bool = Field(default=True, description="Whether column is filterable")
    hidden: bool = Field(default=False, description="Hide column by default")


class SchemaDefinition(BaseModel):
    """Defines how module results should be displayed."""
    view: ViewType = Field(default=ViewType.TABLE, description="Primary display mode")
    columns: List[ColumnDefinition] = Field(default_factory=list, description="Column definitions")

    # Optional gallery-specific settings
    thumbnail_key: Optional[str] = Field(default="screenshot_url", description="Key for thumbnail URL in gallery view")
    caption_keys: List[str] = Field(default_factory=lambda: ["host", "port", "protocol"], description="Keys to show as caption")

    # Optional grouping
    group_by: Optional[str] = Field(default=None, description="Key to group results by")


class ModuleInfo(BaseModel):
    """Module identification and metadata."""
    name: str = Field(..., description="Human-readable module name")
    slug: str = Field(..., description="URL-safe identifier")
    version: str = Field(default="1.0.0", description="Module version")
    author: str = Field(default="", description="Module author")
    description: str = Field(default="", description="Module description")
    category: ModuleCategory = Field(default=ModuleCategory.ENUMERATION, description="Module category for UI grouping")


class RunMetadata(BaseModel):
    """Metadata about a specific module execution."""
    started_at: Optional[datetime] = Field(default=None, description="Execution start time")
    completed_at: Optional[datetime] = Field(default=None, description="Execution end time")
    target_count: int = Field(default=0, description="Number of targets scanned")
    success_count: int = Field(default=0, description="Number of successful results")
    error_count: int = Field(default=0, description="Number of errors")
    exported_formats: List[str] = Field(default_factory=lambda: ["json"], description="Formats exported")

    # Optional execution context
    command_line: Optional[str] = Field(default=None, description="CLI command used")
    workspace: Optional[str] = Field(default=None, description="Workspace path")


class AssetReferences(BaseModel):
    """References to files generated by the module."""
    screenshots: List[str] = Field(default_factory=list, description="Screenshot file paths (relative to module dir)")
    files: List[str] = Field(default_factory=list, description="Additional data files")


# ----------------------------------------------------------------------
# Main Schema
# ----------------------------------------------------------------------
class CygorResult(BaseModel):
    """
    Root schema for cygor-result.json.

    This is the universal output format that all cygor modules emit.
    The web UI reads this schema to automatically render results.
    """
    module: ModuleInfo = Field(..., description="Module identification")
    metadata: RunMetadata = Field(default_factory=RunMetadata, description="Execution metadata")
    schema_def: SchemaDefinition = Field(default_factory=SchemaDefinition, alias="schema", description="Display schema")
    results: List[Dict[str, Any]] = Field(default_factory=list, description="Result rows/items")
    assets: AssetReferences = Field(default_factory=AssetReferences, description="Generated files")

    model_config = {
        "populate_by_name": True,  # Allow both 'schema' and 'schema_def'
        "json_schema_extra": {
            "examples": [
                {
                    "module": {
                        "name": "SMB Explorer",
                        "slug": "smbexplorer",
                        "version": "2.0.0",
                        "category": "network-shares"
                    },
                    "metadata": {
                        "started_at": "2025-12-15T10:30:00Z",
                        "completed_at": "2025-12-15T10:31:45Z",
                        "target_count": 15,
                        "success_count": 12
                    },
                    "schema": {
                        "view": "table",
                        "columns": [
                            {"key": "ip", "label": "IP Address", "type": "ip"},
                            {"key": "share", "label": "Share Name", "type": "string"},
                            {"key": "permissions", "label": "Permissions", "type": "badge"}
                        ]
                    },
                    "results": [
                        {"ip": "192.168.1.100", "share": "C$", "permissions": "Read Only"}
                    ],
                    "assets": {
                        "screenshots": [],
                        "files": ["smb_files.json"]
                    }
                }
            ]
        }
    }

    def to_json(self, indent: int = 2) -> str:
        """Serialize to JSON string."""
        return self.model_dump_json(indent=indent, by_alias=True)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return self.model_dump(by_alias=True)

    @classmethod
    def from_json_file(cls, path: Union[str, Path]) -> "CygorResult":
        """Load and validate from a JSON file."""
        import json
        path = Path(path)
        data = json.loads(path.read_text(encoding="utf-8"))
        return cls.model_validate(data)

    def save(self, path: Union[str, Path]) -> None:
        """Save to a JSON file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.to_json(), encoding="utf-8")


# ----------------------------------------------------------------------
# Helper functions
# ----------------------------------------------------------------------
def make_column(key: str, label: str, col_type: str = "string", **kwargs) -> ColumnDefinition:
    """Convenience function to create a column definition."""
    return ColumnDefinition(key=key, label=label, type=ColumnType(col_type), **kwargs)


def make_table_schema(columns: List[ColumnDefinition], **kwargs) -> SchemaDefinition:
    """Create a table-view schema."""
    return SchemaDefinition(view=ViewType.TABLE, columns=columns, **kwargs)


def make_gallery_schema(
    columns: List[ColumnDefinition],
    thumbnail_key: str = "screenshot_url",
    caption_keys: Optional[List[str]] = None,
    **kwargs
) -> SchemaDefinition:
    """Create a gallery-view schema."""
    return SchemaDefinition(
        view=ViewType.GALLERY,
        columns=columns,
        thumbnail_key=thumbnail_key,
        caption_keys=caption_keys or ["host", "port", "protocol"],
        **kwargs
    )


# ----------------------------------------------------------------------
# Predefined column sets for common use cases
# ----------------------------------------------------------------------
COMMON_COLUMNS = {
    "host": make_column("host", "Host", "ip"),
    "ip": make_column("ip", "IP Address", "ip"),
    "port": make_column("port", "Port", "string"),
    "protocol": make_column("protocol", "Protocol", "badge"),
    "status": make_column("status", "Status", "badge"),
    "url": make_column("url", "URL", "url"),
    "screenshot_url": make_column("screenshot_url", "Screenshot", "screenshot"),
    "service": make_column("service", "Service", "string"),
    "version": make_column("version", "Version", "string"),
    "banner": make_column("banner", "Banner", "code"),
}


def get_common_column(name: str) -> ColumnDefinition:
    """Get a predefined common column by name."""
    if name not in COMMON_COLUMNS:
        raise ValueError(f"Unknown common column: {name}. Available: {list(COMMON_COLUMNS.keys())}")
    return COMMON_COLUMNS[name].model_copy()
